/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlktx;

import NhanVienKeToanMo.TrangChuKT;
import static com.mycompany.qlktx.QLKTX.convertDateFormat;
import static com.mycompany.qlktx.QLKTX.getConnection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class popup_thongtinsv extends javax.swing.JFrame {
    String mssv_temp;
    private JFrame preFrame;

    public popup_thongtinsv(String mssv, JFrame preFrame) {
        this.preFrame = preFrame;
        initComponents();
        thietlapManHinh(mssv);
        mssv_temp = mssv;
        if (txtTinhtrangO.getText().equals("Đang ở") || txtTinhtrangO.getText().equals("Đã trả phòng"))
            btCapNhat2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbTTSV = new javax.swing.JLabel();
        btCapNhat2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbMSSV = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTungay = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDenngay = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtNgaytraphong = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTinhtrangO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbTTSV.setBackground(new java.awt.Color(255, 255, 255));
        lbTTSV.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTTSV.setForeground(new java.awt.Color(83, 160, 219));
        lbTTSV.setText("Thông tin sinh viên");

        btCapNhat2.setBackground(new java.awt.Color(93, 163, 217));
        btCapNhat2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btCapNhat2.setForeground(new java.awt.Color(255, 255, 255));
        btCapNhat2.setText("Cho phép ở");
        btCapNhat2.setActionCommand("");
        btCapNhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhat2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel5.setText("Họ Tên:");

        lbMSSV.setBackground(new java.awt.Color(255, 255, 255));
        lbMSSV.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lbMSSV.setText("MSSV:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel6.setText("Giới Tính:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel7.setText("Ngày Sinh: ");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel8.setText("E-mail: ");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel24.setText("Phòng:");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel25.setText("SDT:");

        txtMSSV.setEditable(false);
        txtMSSV.setBackground(new java.awt.Color(254, 254, 254));
        txtMSSV.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtMSSV.setBorder(null);

        txtNgaySinh.setEditable(false);
        txtNgaySinh.setBackground(new java.awt.Color(254, 254, 254));
        txtNgaySinh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtNgaySinh.setBorder(null);

        txtHoTen.setEditable(false);
        txtHoTen.setBackground(new java.awt.Color(254, 254, 254));
        txtHoTen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtHoTen.setBorder(null);

        txtGioiTinh.setEditable(false);
        txtGioiTinh.setBackground(new java.awt.Color(254, 254, 254));
        txtGioiTinh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtGioiTinh.setBorder(null);

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(254, 254, 254));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtEmail.setBorder(null);

        txtSDT.setEditable(false);
        txtSDT.setBackground(new java.awt.Color(254, 254, 254));
        txtSDT.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtSDT.setBorder(null);

        txtPhong.setEditable(false);
        txtPhong.setBackground(new java.awt.Color(254, 254, 254));
        txtPhong.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtPhong.setBorder(null);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel26.setText("Ngày bắt đầu ở:");

        txtTungay.setEditable(false);
        txtTungay.setBackground(new java.awt.Color(254, 254, 254));
        txtTungay.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtTungay.setBorder(null);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel27.setText("Ngày hết hạn ở:");

        txtDenngay.setEditable(false);
        txtDenngay.setBackground(new java.awt.Color(254, 254, 254));
        txtDenngay.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtDenngay.setBorder(null);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel28.setText("Ngày trả phòng:");

        txtNgaytraphong.setEditable(false);
        txtNgaytraphong.setBackground(new java.awt.Color(254, 254, 254));
        txtNgaytraphong.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtNgaytraphong.setBorder(null);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel29.setText("Tình trạng ở:");

        txtTinhtrangO.setEditable(false);
        txtTinhtrangO.setBackground(new java.awt.Color(254, 254, 254));
        txtTinhtrangO.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtTinhtrangO.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(txtNgaytraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMSSV, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtTungay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDenngay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinhtrangO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbTTSV))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btCapNhat2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbTTSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMSSV)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinhtrangO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaytraphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(btCapNhat2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCapNhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhat2ActionPerformed
        int ret = JOptionPane.showConfirmDialog(null, "Xác nhận cập nhật", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String sdt = txtSDT.getText();

            Connection con = getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
            }

            try {           
                String sql = "UPDATE CUTRU SET TINHTRANGO = 1 WHERE MSSV = ? AND TINHTRANGO = 0";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1, mssv_temp);

                ResultSet rs = pstmt.executeQuery();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Success", JOptionPane.INFORMATION_MESSAGE);
                txtTinhtrangO.setText("Đang ở");
                ((DSSinhVien)preFrame).loadData();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btCapNhat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void thietlapManHinh(String mssv) {
        // Ngăn cản người dùng chỉnh sửa
        txtMSSV.setEditable(false); 
        txtHoTen.setEditable(false);
        txtNgaySinh.setEditable(false);
        txtGioiTinh.setEditable(false);
        txtEmail.setEditable(false);
        txtSDT.setEditable(false);
        txtPhong.setEditable(false);
        txtTungay.setEditable(false);
        txtDenngay.setEditable(false);
        txtTinhtrangO.setEditable(false);
        txtNgaytraphong.setEditable(false);
        
        // Kết nối đến CSDL và hiển thị dữ liệu
        layTTSV(mssv);
    }
    
    private void layTTSV(String mssv) {
        Connection con = getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(mssv);
        try {
//            String sql = "SELECT C.MAPHONG, S.TENSV, S.NGSINH, S.GIOITINH, S.EMAIL, S.SDT FROM SINHVIEN S LEFT JOIN ( SELECT * FROM CUTRU WHERE MSSV = ? AND NGAYTRAPHONG IS NULL) C ON C.MSSV = S.MSSV WHERE S.MSSV = ?";
//            if(txtTinhtrangO.getText().equals("Đã trả phòng"))
//            String sql1 = "SELECT * FROM SINHVIEN S JOIN CUTRU C ON S.MSSV = C.MSSV "
//                    + "WHERE S.MSSV = ? "
//                    + "AND NGAYTRAPHONG = SELECT MAX(C.NGAYTRAPHONG) FROM SINHVIEN S JOIN CUTRU C ON S.MSSV = C.MSSV WHERE S.MSSV = ?";
            String sql1 = "SELECT * " +
                     "FROM SINHVIEN S JOIN CUTRU C ON S.MSSV = C.MSSV " +
                     "WHERE S.MSSV = ? " +
                     "ORDER BY " +
                     "    CASE " +
                     "        WHEN NGAYTRAPHONG IS NULL THEN NGAYTRAPHONG " +
                     "        WHEN TUNGAY IS NOT NULL THEN TUNGAY " +
                     "    END DESC " +
                     "FETCH FIRST 1 ROW ONLY";
            PreparedStatement pstmt = con.prepareStatement(sql1);
            pstmt.setString(1, mssv);
            pstmt.setString(1, mssv);

            ResultSet rs = pstmt.executeQuery();
                                    
            while (rs.next()) {
                String tenSv = rs.getString("TENSV");
                String ngSinh = convertDateFormat(rs.getString("NGSINH"));
                int gioitinh = rs.getInt("GIOITINH");
                String gioitinhS;
                if(gioitinh == 0)
                    gioitinhS = "Nữ";
                else if(gioitinh == 1);
                    gioitinhS = "Nam";
                String email = rs.getString("EMAIL");
                String sdt = rs.getString("SDT");                 
                String maPhong = rs.getString("MAPHONG");
                Date tungay = rs.getDate("TUNGAY");
                Date denngay = rs.getDate("DENNGAY");
                int tinhtrango = rs.getInt("TINHTRANGO");
                String tinhtrangoS;
                if(tinhtrango == 0)
                    tinhtrangoS = "Đã đăng ký";
                else if(tinhtrango == 1)
                    tinhtrangoS = "Đang ở";
                else if(tinhtrango == 2)
                    tinhtrangoS = "Đã trả phòng";
                else
                    tinhtrangoS = "Không xác định";
                
                Date ngaytraphong = rs.getDate("NGAYTRAPHONG");
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); 
                
                txtMSSV.setText(mssv);
                txtHoTen.setText(tenSv);
                txtNgaySinh.setText(ngSinh);
                txtGioiTinh.setText(gioitinhS);
                txtEmail.setText(email);
                txtSDT.setText(sdt);
                txtPhong.setText(maPhong);
                txtTungay.setText(sdf.format(tungay));
                txtDenngay.setText(sdf.format(denngay));
                txtTinhtrangO.setText(tinhtrangoS);
                if(ngaytraphong != null)
                    txtNgaytraphong.setText(sdf.format(ngaytraphong));
            }
            rs.close();
            pstmt.close();
            con.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi trong quá trình truy vấn cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbMSSV;
    private javax.swing.JLabel lbTTSV;
    private javax.swing.JTextField txtDenngay;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgaytraphong;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTinhtrangO;
    private javax.swing.JTextField txtTungay;
    // End of variables declaration//GEN-END:variables
}
